#
# (c) Copyright 2025 Swiss Post Ltd.
#

app:
  component:
    available:
  directory:
    output: workspace
  certificate:
    country: CH
    state: NEUCHATEL
    locality: Neuchatel
    organization: DT_
  resetMode: NEVER_ENABLED

# Logging
spring:
  main:
    banner-mode: LOG
  output:
    ansi:
      enabled: always

logging:
  file:
    name: logs/direct-trust-tool.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 0
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.log
